version: '2'
services:
  drupal:
    build:
      context: ./
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/app
      - ./log:/log
      - /files/private
      - /files/temporary
  drush:
    image: drush/drush:8
    volumes_from:
      - drupal
  drupalconsole:
    image: drupalconsole/console:1.0
    volumes_from:
      - drupal
