version: '2'
services:
  front:
    build:
      context: ./
    ports:
      - "80:80"
      - "443:443"
    links:
      - db
    volumes:
      - ./app:/app
      - ./log:/log
  db:
    image: mariadb:10.1.18
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
  drush:
    image: drush/drush:8
    volumes_from:
      - front
  drupal:
    image: drupalconsole/console:1.0
    volumes_from:
      - front
